//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by cdm.rc
//
#define IDR_MANIFEST                    1
#define IDOK2                           2
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define ID_UPDATE_DIALOG                102
#define IDD_MAIN_DIALOG                 102
#define IDS_TOTALSIZE                   102
#define IDS_TOTALTIME                   103
#define IDS_DRIVENAME                   104
#define IDR_MAINFRAME                   128
#define IDR_MAINMENU                    129
#define ID_EXIT                         130
#define ID_VIEW_VERSION                 131
#define IDR_TOCFRAME                    132
#define IDR_MENU1                       133
#define ID_TOOL_TOCFROMSESSION          135
#define ID_VIEW_TOCWINDOW               136
#define ID_TOOL_CREATEIMAGE             138
#define IDD_READSETTING                 139
#define IDD_READPROGRESS                140
#define ID_VIEW_LOG                     141
#define IDR_LOGFRAME                    142
#define ID_WINDOW_CLOSE                 143
#define IDB_LOGTYPE                     143
#define IDD_SETTING                     144
#define IDD_READTRACK                   145
#define ID_TOOL_READTRACK               146
#define ID_SAVELOG                      147
#define ID_READSETTING                  148
#define IDD_SUBQPROGRESS                149
#define ID_TOOL_SUBQ                    150
#define ID_TOOL_MASTERING               152
#define IDD_MASTERING_FILE              153
#define IDR_MASTERING_FILE              154
#define ID_155                          155
#define IDB_BITMAP1                     156
#define IDB_FILE_TREE                   156
#define IDB_FILE_LIST                   157
#define ID_EDIT_ADDFOLDER               158
#define ID_EDIT_LABEL                   159
#define ID_EDIT_DELETEFOLDER            160
#define ID_EDIT_ADDFILE                 161
#define ID_EDIT_ADDAUDIO                162
#define IDD_CREATPROGRESS               163
#define ID_EDIT_DELETETRACK             164
#define ID_EDIT_ADDDATA                 165
#define ID_166                          166
#define IDD_CALCMSF                     167
#define ID_TOOL_MSF                     168
#define ID_CD_WRITE_IMAGE               169
#define IDD_WRITEPROGRESS               170
#define IDD_WRITESETTING                171
#define IDD_ERASE                       172
#define ID_CD_ERASE                     173
#define ID_HIDE_EXECUTE                 175
#define ID_CD_ERASE_FAST                176
#define ID_CD_RECOGNIZE                 177
#define IDI_ICON1                       178
#define IDD_SELECT_DRIVE                179
#define ID_CD_DUPLICATE                 180
#define ID_181                          181
#define IDD_DRIVE_CAPABILITY            182
#define ID_DRIVE_CAPABILITY             183
#define ID_POPUPMENU_185                185
#define ID_POPUPMENU_TEST               186
#define ID_TEST_A                       187
#define ID_FILE_SAVETXT                 188
#define ID_FILE_SAVEHTML                189
#define ID_FILE_SAVECSV                 190
#define ID_TOOL_EJECT                   191
#define IDD_LANGUAGE                    192
#define ID_LANGUAGE                     193
#define IDB_B_CREATE_IMAGE              194
#define IDB_B_WRITE_IMAGE               195
#define IDB_B_DUPLICATE                 196
#define ID_196                          196
#define IDB_B_READ_TRACK                197
#define ID_197                          197
#define IDB_B_MASTERING                 198
#define ID_EDIT_INSERTFOLDER            198
#define IDB_B_SUBQ                      199
#define ID_199                          199
#define IDB_B_RECOGNIZE                 200
#define ID_CLEARLOG                     200
#define IDB_B_EXIT                      201
#define ID_CD_201                       201
#define ID_FILE_SAVECUE                 202
#define ID_202                          202
#define IDD_MASTERING_1                 203
#define IDD_MASTERING_2                 204
#define ID_204                          204
#define IDD_MASTERING_3                 205
#define ID_205                          205
#define ID_HELP_HELP                    206
#define IDD_SETTING_1                   207
#define IDD_SETTING_2                   208
#define IDD_SETTING_3                   209
#define IDD_SETTING_4                   210
#define IDD_READSETTING_1               211
#define IDD_READSETTING_2               212
#define IDD_READSETTING_3               213
#define IDD_READSETTING_4               214
#define IDD_DIALOG1                     215
#define IDD_MESSAGE                     215
#define IDB_ABOUT                       217
#define IDC_DRIVELIST                   1003
#define IDC_IMAGENAME                   1007
#define IDC_BROWSFILE                   1008
#define IDC_MESSAGE                     1009
#define ID_VERSTRING                    1010
#define IDC_PERCENT                     1011
#define IDC_PROGRESS                    1012
#define IDC_LOG                         1013
#define IDC_CREATECUE                   1016
#define IDC_CREATEIMG                   1017
#define IDC_WRITENULL                   1018
#define IDC_SESSIONLIST                 1021
#define IDC_AUDIOSPEED                  1023
#define IDC_DATASPEED                   1024
#define IDC_SETTING                     1024
#define IDC_AUDIOMETHOD                 1025
#define IDC_DATASPEED2                  1026
#define IDC_BROWS                       1027
#define IDC_FILELIST                    1028
#define IDC_IGNORE_READERROR            1031
#define IDC_MULTI                       1032
#define IDC_SWAPCHANNEL                 1033
#define IDC_AUTODETECT_COMMAND          1034
#define IDC_SECTOR                      1037
#define IDC_SUBQMETHOD                  1038
#define IDC_TREE                        1039
#define IDC_SUBQSPEED                   1039
#define IDC_LIST                        1040
#define IDC_TRACKLIST                   1041
#define IDC_FILEDLG                     1042
#define IDC_CREATE_ISO                  1043
#define ID_CREATE_IMAGE                 1043
#define IDC_VOLUME_LABEL                1044
#define IDC_REVISION                    1046
#define IDC_STATIC_TXT1                 1047
#define IDC_STATIC_TXT2                 1048
#define IDC_STATIC_TXT3                 1049
#define IDC_MSF_M                       1051
#define IDC_MSF_S                       1052
#define IDC_MSF_F                       1053
#define IDC_MSF150_M                    1054
#define IDC_MSF150_S                    1055
#define IDC_MSF150_F                    1056
#define IDC_CALC_MSF                    1057
#define IDC_LBA                         1058
#define IDC_LBAHEX                      1059
#define IDC_CALC_MSF150                 1060
#define IDC_CALC_LBA                    1061
#define IDC_CALC_LBAHEX                 1062
#define IDC_ZERO                        1063
#define IDC_CUEFILE                     1066
#define IDC_BROWSE_CUESHEET             1067
#define IDC_BURNPROOF                   1068
#define IDC_TESTMODE                    1069
#define IDC_OPC                         1070
#define IDC_EJECT_TRAY                  1071
#define IDC_WRITEMODE_1                 1072
#define IDC_WRITEMODE_2                 1074
#define IDC_WRITEMODE_3                 1075
#define IDC_WRITEMODE_4                 1076
#define IDC_CHECK_DRIVE                 1077
#define IDC_WRITESPEED                  1078
#define IDC_DRIVENAME                   1078
#define IDC_DRIVENAME2                  1079
#define IDC_FAST_ERRORSKIP              1079
#define IDC_BUFFERSIZE                  1084
#define IDC_BUFFERSIZE_TXT              1085
#define IDC_WRITER                      1085
#define IDC_SELECTDRIVE                 1086
#define IDC_DEFAULT_COMMAND             1086
#define IDC_ANALYZE_SUBQ                1088
#define IDC_MULTISESSION                1089
#define IDC_COPYTEMPFILE                1090
#define IDC_BROWS_TEMPFILE              1091
#define IDC_BUTTON1                     1094
#define IDC_WRITING                     1094
#define IDC_BROWS_ASPI                  1094
#define ID_CREATE_CD                    1094
#define IDC_UP_ORDER                    1094
#define IDC_IMAGESIZE                   1095
#define IDC_BROWS_LOG                   1095
#define IDC_DOWN_ORDER                  1095
#define IDC_AUTODETECT                  1096
#define IDC_BROWS_SKIN                  1096
#define IDC_COMMAND_FRAME               1097
#define IDC_BROWS_WAV_SUCCESS           1097
#define PERCENT                         1098
#define IDC_BROWS_WAV_FAIL              1098
#define IDC_ALWAYS_TOP                  1099
#define IDC_HA                          1100
#define IDC_TGT                         1101
#define IDC_SET_ASPI                    1101
#define IDC_LUN                         1102
#define IDC_ASPI_DLL                    1102
#define IDC_VENDOR                      1103
#define IDC_BURST_ERROR_SCAN            1103
#define IDC_AUTOSAVE_LOG                1103
#define IDC_LOG_FILE                    1104
#define IDC_RAWFLAG                     1104
#define IDC_TAB                         1105
#define IDC_SUBTITLE                    1105
#define IDC_SET_SKIN                    1105
#define IDC_SAO                         1106
#define IDC_AUTHOR                      1106
#define IDC_SKIN_FILE                   1106
#define IDC_RAW96                       1107
#define IDC_SET_WAV_SUCCESS             1107
#define IDC_RAW16                       1108
#define IDC_WAV_SUCCESS_FILE            1108
#define IDC_RAW96P                      1109
#define IDC_SET_WAV_FAIL                1109
#define IDC_SAO_TEST                    1110
#define IDC_WAV_FAIL_FILE               1110
#define IDC_RAW96_TEST                  1111
#define IDC_RAW16_TEST                  1112
#define IDC_RAW96P_TEST                 1113
#define IDC_STATIC0                     1114
#define IDC_STATIC1                     1115
#define IDC_STATIC2                     1116
#define IDC_STATIC3                     1117
#define IDC_STATIC4                     1118
#define IDC_STATIC5                     1119
#define IDC_STATIC6                     1120
#define IDC_STATIC7                     1121
#define IDC_STATIC8                     1122
#define IDC_STATIC9                     1123
#define IDC_STATIC10                    1124
#define IDC_STATIC11                    1125
#define IDC_TAB1                        1128
#define IDC_STAB                        1128
#define IDC_ANALYZE_PREGAP              1129
#define IDC_NOTIFY_TRUNCATED            1137
#define ID_TRACK_ISO                    1138
#define IDC_PRIORITY                    1138
#define IDC_PRIORITY_TXT                1139
#define IDC_EXPLORER                    1140
#define IDC_ADDRESS                     1144
#define IDC_USE_SPTI                    1145
#define IDC_COMBO2                      1149
#define IDC_PROTECTION_FEATURES         1149
#define IDC_EXTMENU                     1150
#define IDC_ENGINELIST                  1154
#define ID_HELP_VIS                     32774
#define ID_RS_HOME                      32775

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        219
#define _APS_NEXT_COMMAND_VALUE         32776
#define _APS_NEXT_CONTROL_VALUE         1157
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
